---
- name: Common | Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Common | Install prerequisite packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - vim
      - net-tools
    state: present

- name: Common | Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: true

- name: Common | Load required kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Common | Configure sysctl params for Kubernetes networking
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf.call-iptables = 1
      net.bridge.bridge-nf.call-ip6tables = 1
      net.ipv4.ip_forward = 1
    mode: "0644"

- name: Common | Apply sysctl params
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Common | Create dir for keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
